application: gae-go-dart-skeleton
version: 1
runtime: go
api_version: go1

handlers:
# Handler for the main page
- url: /
  static_files : client/web/index.html
  upload: client/web/index.html

# Handlers to get rid of .dart file mime type warnings when uploading
- url: /packages/(.*\.dart)
  mime_type: application/dart
  static_files: client/packages/\1
  upload: client/packages/(.*\.dart)

- url: /components/(.*\.dart)
  mime_type: application/dart
  static_files: client/lib/components/\1
  upload: client/lib/components/(.*\.dart)

- url: /models/(.*\.dart)
  mime_type: application/dart
  static_files: client/lib/models/\1
  upload: client/lib/models/(.*\.dart)

- url: /services/(.*\.dart)
  mime_type: application/dart
  static_files: client/lib/services/\1
  upload: client/lib/services/(.*\.dart)

# Handler for dart packages
- url: /packages
  static_dir: client/packages

# Handler for libraries
- url: /components
  static_dir: client/lib/components

- url: /services
  static_dir: client/lib/services

- url: /models
  static_dir: client/lib/models

# All other requests are handled by the Go code
- url: /.*
  script: _go_app

