application: gae-go-dart-skeleton
version: 1
runtime: go
api_version: go1

handlers:
# Handler for dart script in dev server
- url: /(.*\.dart)
  static_files : web/web/\1
  upload: web/web/(.*\.dart)

# Handler for JavaScript after pub build
# - url: /(.*\.js)
#   static_files : web/build/web/\1
#   upload: web/build/web/(.*\.js)

# Handler for all package files
- url: /packages/(.*\.dart|.*\.js|.*\.html)
  static_files: web/packages/\1
  upload: web/packages/(.*\.dart|.*\.js|.*\.html)

# All other requests are handled by the Go code
- url: /.*
  script: _go_app

